#!/usr/bin/env bash
# Hermetic smoke test for the Claude Code lifecycle adapter (Fáze A auto-wire, 2026-07-18).
# Parity with test_codex_adapter.sh; adds the Claude-only SessionEnd event + the auto-wire gate.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
plugin_root="$(cd "$here/.." && pwd)"
dispatch="$plugin_root/adapters/claude-code/hook_dispatch.sh"
hooks_json="$plugin_root/hooks/hooks.json"
report="$plugin_root/scripts/capability_report.sh"

T="$(mktemp -d "${TMPDIR:-/tmp}/fmc-claude-adapter.XXXXXX")"
trap 'rm -rf "$T"' EXIT
pass=0 fail=0
ok()  { pass=$((pass+1)); printf '  PASS  %s\n' "$1"; }
bad() { fail=$((fail+1)); printf '  FAIL  %s\n' "$1"; }
check() { if eval "$2"; then ok "$1"; else bad "$1"; fi; }

project="$T/project"
mkdir -p "$project"
bash "$plugin_root/scripts/install_project_template.sh" --with-scripts "$project" >/dev/null
printf '%s\n' \
  '# INDEX — fixture' '' '> Claude adapter fixture.' '' \
  '<!-- gen_index:auto — the table below is generated by gen_index.sh; do not hand-edit, it regenerates -->' \
  > "$project/INDEX.md"
bash "$plugin_root/scripts/memory_route.sh" --memory-dir "$project/memory" \
  --text "Claude adapter defaultně zapojuje všech deset FMC nervů (parita s Codexem)." \
  --kind fact --commit --approved-by test --reason "Claude adapter fixture" \
  --importance 4 --origin approved --slug claude-adapter-vsechny-nervy >/dev/null
bash "$plugin_root/scripts/ledger_carry.sh" --memory-dir "$project/memory" \
  --item "PENDING(Farky): Potvrdit Claude adapter fixture / testuje auto-wire boot nerv / rozhodnuti uzavre test (proposed 2026-07-18)" >/dev/null

echo '== 1. shipped hooks.json auto-wires the dispatch (all four events) =='
check 'hooks/hooks.json is valid JSON' 'python3 -m json.tool "$hooks_json" >/dev/null 2>&1'
check 'hooks.json calls the Claude dispatch' 'grep -qF "adapters/claude-code/hook_dispatch.sh" "$hooks_json"'
check 'all four lifecycle events wired' \
  'grep -q '\''"SessionStart"'\'' "$hooks_json" && grep -q '\''"UserPromptSubmit"'\'' "$hooks_json" && grep -q '\''"SessionEnd"'\'' "$hooks_json" && grep -q '\''"PreCompact"'\'' "$hooks_json"'

echo '== 2. SessionStart runs the FMC nerves sequentially (gate ON) =='
payload="{\"session_id\":\"claude-adapter-test\",\"source\":\"startup\"}"
out="$(cd "$project" && printf '%s' "$payload" | CLAUDE_PLUGIN_ROOT="$plugin_root" CLAUDE_PROJECT_DIR="$project" bash "$dispatch" session-start)"
check 'SessionStart identifies FMC' 'printf "%s" "$out" | grep -q "FMC active"'
check 'SessionStart injects the regenerated atom registry' \
  'printf "%s" "$out" | grep -q "REJSTŘÍK" && printf "%s" "$out" | grep -q "claude-adapter-vsechny-nervy"'
check 'SessionStart surfaces pending human decisions' \
  'printf "%s" "$out" | grep -q "PENDING DECISIONS" && printf "%s" "$out" | grep -q "Potvrdit Claude adapter fixture"'
check 'SessionStart injects the whole-repo map for a managed root INDEX' \
  'printf "%s" "$out" | grep -q "repo — what lives where"'
check 'close-state uses hook session_id and never invents nosession' \
  '[ -f "$project/memory/.close-state/claude-adapter-test.env" ] && [ ! -f "$project/memory/.close-state/nosession.env" ]'
check 'capability_report stays SILENT (auto-wired = all-on, no fragment nag)' \
  '! printf "%s" "$out" | grep -q "wire them" && ! printf "%s" "$out" | grep -q "of 10 wired"'

echo '== 3. UserPromptSubmit captures, redacts and recalls =='
pp="{\"session_id\":\"claude-adapter-test\",\"prompt\":\"Ktere FMC nervy zapojuje Claude adapter defaultne? sk-ABCDEFGHIJKLMNOPQRST\"}"
pout="$(cd "$project" && printf '%s' "$pp" | CLAUDE_PLUGIN_ROOT="$plugin_root" CLAUDE_PROJECT_DIR="$project" bash "$dispatch" user-prompt-submit)"
check 'prompt hook emits a matching recall pointer' \
  'printf "%s" "$pout" | grep -q "RECALL" && printf "%s" "$pout" | grep -q "claude-adapter-vsechny-nervy"'
check 'prompt reached the session journal' 'grep -q "Ktere FMC nervy" "$project/memory/session.md"'
check 'secret-looking value was redacted' \
  'grep -q "\[REDACTED\]" "$project/memory/session.md" && ! grep -q "sk-ABCDEFGHIJKLMNOPQRST" "$project/memory/session.md"'
check 'prompt hook fires the behavioral lapač/skill reflex (enabled, host-specific tool)' \
  'printf "%s" "$pout" | grep -q "FMC reflex" && printf "%s" "$pout" | grep -q "cumulative visible to-do ledger" && printf "%s" "$pout" | grep -q "TodoWrite"'

echo '== 4. SessionEnd finalizes close-debt (Claude-only event) =='
# Two prompts already? one above; add one more so work_threshold (2) is met -> UNCLOSED marker on end.
pp2="{\"session_id\":\"claude-adapter-test\",\"prompt\":\"Druhy prompt pro splneni work threshold.\"}"
(cd "$project" && printf '%s' "$pp2" | CLAUDE_PLUGIN_ROOT="$plugin_root" CLAUDE_PROJECT_DIR="$project" bash "$dispatch" user-prompt-submit) >/dev/null
end_payload="{\"session_id\":\"claude-adapter-test\"}"
(cd "$project" && printf '%s' "$end_payload" | CLAUDE_PLUGIN_ROOT="$plugin_root" CLAUDE_PROJECT_DIR="$project" bash "$dispatch" session-end) >/dev/null 2>&1
check 'SessionEnd left an UNCLOSED marker (work + no conscious close)' \
  'find "$project/memory/.close-state" -maxdepth 1 -name '\''UNCLOSED-*.env'\'' -print -quit 2>/dev/null | grep -q .'

echo '== 5. PreCompact + gate OFF (inert outside an FMC project) =='
compact_out="$(cd "$project" && printf '%s' "$payload" | CLAUDE_PLUGIN_ROOT="$plugin_root" CLAUDE_PROJECT_DIR="$project" bash "$dispatch" pre-compact)"
check 'PreCompact surfaces continuity advice' 'printf "%s" "$compact_out" | grep -q "FMC PreCompact"'
outside="$T/outside"; mkdir -p "$outside"
outside_out="$(cd "$outside" && printf '%s' "$payload" | CLAUDE_PLUGIN_ROOT="$plugin_root" CLAUDE_PROJECT_DIR="$outside" bash "$dispatch" session-start)"
check 'adapter is inert outside an FMC project (no memory/MEMORY.md)' '[ -z "$outside_out" ] && [ ! -e "$outside/memory" ]'

echo '== 6. capability report + no-silent-fallback =='
status_out="$(bash "$report" --status --host claude --plugin-dir "$plugin_root" --project-dir "$project")"
check 'Claude capability report sees all ten nerves wired' \
  'printf "%s" "$status_out" | grep -q "offered=10 wired=10"'
fake_plugin="$T/fake-plugin"; mkdir -p "$fake_plugin/adapters/claude-code"
cp "$dispatch" "$fake_plugin/adapters/claude-code/hook_dispatch.sh"
fallback_out="$(cd "$project" && printf '%s' "$payload" | CLAUDE_PLUGIN_ROOT="$fake_plugin" CLAUDE_PROJECT_DIR="$project" bash "$fake_plugin/adapters/claude-code/hook_dispatch.sh" session-start)"
check 'missing engine scripts are reported as FMC FALLBACK' \
  'printf "%s" "$fallback_out" | grep -q "FMC FALLBACK"'

echo
echo "== test_claude_adapter: $pass passed, $fail failed =="
[ "$fail" -eq 0 ]
