#!/usr/bin/env bash
# Hermetic smoke test for the Codex lifecycle adapter.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
plugin_root="$(cd "$here/.." && pwd)"
dispatch="$plugin_root/adapters/codex/hook_dispatch.sh"
hooks_json="$plugin_root/adapters/codex/hooks.json"
report="$plugin_root/scripts/capability_report.sh"

T="$(mktemp -d "${TMPDIR:-/tmp}/fmc-codex-adapter.XXXXXX")"
trap 'rm -rf "$T"' EXIT
pass=0 fail=0
ok()  { pass=$((pass+1)); printf '  PASS  %s\n' "$1"; }
bad() { fail=$((fail+1)); printf '  FAIL  %s\n' "$1"; }
check() { if eval "$2"; then ok "$1"; else bad "$1"; fi; }

project="$T/project"
mkdir -p "$project"
bash "$plugin_root/scripts/install_project_template.sh" --with-scripts "$project" >/dev/null
mkdir -p "$project/docs"
printf '# Guide\n\n> Fixture documentation.\n' > "$project/docs/guide.md"
printf '%s\n' \
  '# INDEX — fixture' \
  '' \
  '> Codex adapter fixture.' \
  '' \
  '<!-- gen_index:auto — the table below is generated by gen_index.sh; do not hand-edit, it regenerates -->' \
  > "$project/INDEX.md"
printf '%s\n' \
  '# INDEX — docs' \
  '' \
  '> Fixture docs.' \
  '' \
  '<!-- gen_index:auto — the table below is generated by gen_index.sh; do not hand-edit, it regenerates -->' \
  > "$project/docs/INDEX.md"
bash "$plugin_root/scripts/memory_route.sh" --memory-dir "$project/memory" \
  --text "Codex adapter defaultně zapojuje všechny FMC nervy pro vlastní paměť projektu." \
  --kind fact --commit --approved-by test --reason "Codex adapter fixture" \
  --importance 4 --origin approved --slug codex-adapter-vsechny-nervy >/dev/null
bash "$plugin_root/scripts/ledger_carry.sh" --memory-dir "$project/memory" \
  --item "PENDING(Farky): Potvrdit Codex adapter fixture / testuje defaultni boot nerv / rozhodnuti uzavre test (proposed 2026-07-18)" >/dev/null

echo '== 1. packaged hook definition =='
check 'Codex manifest points at the dedicated hooks file' \
  'grep -qF '\''"hooks": "./adapters/codex/hooks.json"'\'' "$plugin_root/.codex-plugin/plugin.json"'
if command -v python3 >/dev/null 2>&1; then
  check 'hooks.json is valid JSON' 'python3 -m json.tool "$hooks_json" >/dev/null 2>&1'
else
  check 'hooks.json carries all supported events' \
    'grep -q '\''"SessionStart"'\'' "$hooks_json" && grep -q '\''"UserPromptSubmit"'\'' "$hooks_json" && grep -q '\''"PreCompact"'\'' "$hooks_json"'
fi

echo '== 2. SessionStart runs the FMC nerves sequentially =='
payload="{\"session_id\":\"codex-adapter-test\",\"cwd\":\"$project\",\"hook_event_name\":\"SessionStart\",\"source\":\"startup\"}"
out="$(cd "$project" && printf '%s' "$payload" | PLUGIN_ROOT="$plugin_root" bash "$dispatch" session-start)"
check 'SessionStart identifies FMC' 'printf "%s" "$out" | grep -q "FMC active"'
check 'SessionStart injects the regenerated atom registry' \
  'printf "%s" "$out" | grep -q "REJSTŘÍK" && printf "%s" "$out" | grep -q "codex-adapter-vsechny-nervy"'
check 'SessionStart surfaces pending human decisions' \
  'printf "%s" "$out" | grep -q "PENDING DECISIONS" && printf "%s" "$out" | grep -q "Potvrdit Codex adapter fixture"'
check 'SessionStart injects the whole-repo map for a managed root INDEX' \
  'printf "%s" "$out" | grep -q "repo — what lives where"'
check 'root INDEX was refreshed and lists docs' 'grep -q '\''`docs/`'\'' "$project/INDEX.md"'
check 'memory INDEX was created' '[ -f "$project/memory/INDEX.md" ]'
check 'close-state initialization was written' \
  'find "$project/memory/.close-state" -type f -name '\''*.env'\'' -print -quit 2>/dev/null | grep -q .'

echo '== 3. UserPromptSubmit captures, redacts and recalls =='
prompt_payload="{\"session_id\":\"codex-adapter-test\",\"cwd\":\"$project\",\"hook_event_name\":\"UserPromptSubmit\",\"prompt\":\"Ktere FMC nervy zapojuje Codex adapter defaultne? sk-ABCDEFGHIJKLMNOPQRST\"}"
prompt_out="$(cd "$project" && printf '%s' "$prompt_payload" | PLUGIN_ROOT="$plugin_root" bash "$dispatch" user-prompt-submit)"
check 'prompt hook emits a matching recall pointer' \
  'printf "%s" "$prompt_out" | grep -q "RECALL" && printf "%s" "$prompt_out" | grep -q "codex-adapter-vsechny-nervy"'
check 'prompt reached the session journal' 'grep -q "Ktere FMC nervy" "$project/memory/session.md"'
check 'secret-looking value was redacted' \
  'grep -q "\[REDACTED\]" "$project/memory/session.md" && ! grep -q "sk-ABCDEFGHIJKLMNOPQRST" "$project/memory/session.md"'

echo '== 4. PreCompact and non-FMC boundary =='
compact_out="$(cd "$project" && printf '%s' "$payload" | PLUGIN_ROOT="$plugin_root" bash "$dispatch" pre-compact)"
check 'PreCompact surfaces continuity advice' 'printf "%s" "$compact_out" | grep -q "FMC PreCompact"'
outside="$T/outside"; mkdir -p "$outside"
outside_out="$(cd "$outside" && printf '%s' "$payload" | PLUGIN_ROOT="$plugin_root" bash "$dispatch" session-start)"
check 'adapter is inert outside an FMC project' '[ -z "$outside_out" ] && [ ! -e "$outside/memory" ]'

echo '== 5. capability report and no-silent-fallback =='
status_out="$(bash "$report" --status --host codex --plugin-dir "$plugin_root" --project-dir "$project")"
check 'Codex capability report sees all ten nerves wired' \
  'printf "%s" "$status_out" | grep -q "offered=10 wired=10"'
fake_plugin="$T/fake-plugin"; mkdir -p "$fake_plugin/adapters/codex"
cp "$dispatch" "$fake_plugin/adapters/codex/hook_dispatch.sh"
fallback_out="$(cd "$project" && printf '%s' "$payload" | PLUGIN_ROOT="$fake_plugin" bash "$fake_plugin/adapters/codex/hook_dispatch.sh" session-start)"
check 'missing engine scripts are reported as FMC FALLBACK' \
  'printf "%s" "$fallback_out" | grep -q "FMC FALLBACK"'

echo
echo "== test_codex_adapter: $pass passed, $fail failed =="
[ "$fail" -eq 0 ]
