#!/usr/bin/env bash
# gen_index.sh — generate a folder INDEX (Farky's concept: every main folder carries a mandatory
# manifest of "what it contains + one-line context"). One reusable tool, run per folder.
#
# Two modes:
#   stdout (default):        gen_index.sh <dir> [--title NAME]   -> prints INDEX markdown
#   merge into a file:       gen_index.sh <dir> --merge-into FILE -> keeps the curated header
#                            ABOVE the marker, regenerates only the table below it. Lets an
#                            INDEX.md carry a hand-written kernel/purpose block + an auto manifest.
#
# 1-line context is DERIVED (not hand-written): frontmatter description (inline or block-scalar)
# > blockquote > H1 > first line.
set -uo pipefail

DIR=""; TITLE=""; MERGE=""; TABLE_ONLY=""; COMPACT=""; ALL_FILES=""; INCLUDE_HIDDEN=""; FILES_ONLY=""; FOLDERS_ONLY=""
while [ $# -gt 0 ]; do
  case "${1:-}" in
    --title) TITLE="${2:-}"; shift 2 ;;
    --merge-into) MERGE="${2:-}"; shift 2 ;;
    --table-only) TABLE_ONLY=1; shift ;;   # print just the manifest table (no curated/kernel header)
    --compact) COMPACT=1; shift ;;         # print names only; bounded SessionStart tree view
    --all-files) ALL_FILES=1; shift ;;     # list safe direct files, not only Markdown
    --include-hidden) INCLUDE_HIDDEN=1; shift ;; # include project dotfiles/dirs; trust exclusions still apply
    --files-only) FILES_ONLY=1; shift ;;   # virtual index: direct files, no directory rows
    --folders-only) FOLDERS_ONLY=1; shift ;; # root rollup: directory rows, no direct files
    *) [ -z "$DIR" ] && DIR="$1"; shift ;;
  esac
done
[ -n "$DIR" ] && [ -d "$DIR" ] || { echo "gen_index: need an existing dir" >&2; exit 1; }
[ -n "$TITLE" ] || TITLE="$(basename "$DIR")"
# NB: detection greps the "gen_index:auto" SUBSTRING, so files carrying the old (Czech)
# marker line keep being recognized and regenerate cleanly onto this one (0.1.35).
MARKER='<!-- gen_index:auto — the table below is generated by gen_index.sh; do not hand-edit, it regenerates -->'

desc_line() {
  local f="$1" d=""
  d="$(awk '
    /^---[[:space:]]*$/ { n++; next }
    n==1 && /^description:/ {
      v=$0; sub(/^description:[[:space:]]*/,"",v)
      if (v ~ /^[>|]/) { blk=1; next }
      print v; exit
    }
    n==1 && blk && /^[[:space:]]+[^[:space:]]/ { sub(/^[[:space:]]+/,""); print; exit }
    n==1 && blk && /^[^[:space:]]/ { exit }
  ' "$f" 2>/dev/null)"
  if [ -n "$d" ]; then printf '%s' "$d" | sed -E 's/^["'\'']//; s/["'\'']$//' | sed 's/\. .*$//' | tr -d '\000-\037' | cut -c1-150; return; fi
  d="$(grep -m1 '^> ' "$f" 2>/dev/null | sed 's/^>[[:space:]]*//' | tr -d '\000-\037' | cut -c1-150)"
  if [ -n "$d" ]; then printf '%s' "$d"; return; fi
  d="$(grep -m1 '^# ' "$f" 2>/dev/null | sed 's/^#[[:space:]]*//' | tr -d '\000-\037' | cut -c1-150)"
  if [ -n "$d" ]; then printf '%s' "$d"; return; fi
  grep -m1 -vE '^[[:space:]]*(#|$|<!--|>)' "$f" 2>/dev/null | tr -d '\000-\037' | cut -c1-150
}

# A derived 1-liner can itself contain `|` (a blockquote "Created … | Total …", a
# frontmatter list). Unescaped, it breaks the 2-column markdown table — the renderer reads
# the extra pipes as extra cells (cc_fos field report 2026-07-12). Escape `|` -> `\|` at the
# point of insertion into a table cell (table-specific concern; desc_line stays generic).
esc_cell() { sed 's/|/\\|/g'; }

# A derived 1-liner (esp. the first-line fallback) can slurp a pasted secret. INDEX.md is
# git-tracked, so a key would land in git — Farky red line. Redact before it reaches the file,
# same conservative patterns as journal_prompt.sh (audit 2026-07-12; over-redaction is safe).
redact_secrets() {
  sed -E \
    -e 's/(sk-|sk-ant-|AIza|ghp_|gho_|ghs_|ghu_|ghr_|glpat-|xox[baprs]-)[A-Za-z0-9_-]{16,}/[REDACTED]/g' \
    -e 's/AKIA[0-9A-Z]{16}/[REDACTED]/g' \
    -e 's/([Bb]earer|[Tt]oken|[Pp]assword|[Aa]pi[_-]?key|[Ss]ecret)([=:[:space:]]+)[A-Za-z0-9._-]{12,}/\1\2[REDACTED]/g' \
    -e 's/-----BEGIN[A-Z ]*PRIVATE KEY-----/[REDACTED-KEY]/g'
}

file_kind() {
  local b="$1"
  case "$b" in
    .gitignore) echo "Git ignore rules" ;;
    .gitattributes) echo "Git attributes" ;;
    .editorconfig) echo "Editor configuration" ;;
    *.sh) echo "Shell script" ;;
    *.py) echo "Python source" ;;
    *.js|*.mjs|*.cjs) echo "JavaScript source" ;;
    *.ts|*.tsx) echo "TypeScript source" ;;
    *.json) echo "JSON data/configuration" ;;
    *.yaml|*.yml) echo "YAML data/configuration" ;;
    *.toml) echo "TOML configuration" ;;
    *.html) echo "HTML document" ;;
    *.css) echo "Stylesheet" ;;
    *.svg|*.png|*.jpg|*.jpeg|*.gif|*.webp) echo "Image asset" ;;
    *.pdf) echo "PDF document" ;;
    *.txt) echo "Text file" ;;
    *) echo "Project file" ;;
  esac
}

skip_file() {
  local b="$1"
  case "$b" in
    INDEX.md|.DS_Store|.env|.env.*|.gen_index.*|.capability-snapshot|.fmc-source|.recall-hits.log|*.pem|*.key|*.p12|*.pfx|*credentials*|*Credentials*) return 0 ;;
  esac
  return 1
}

skip_dir() {
  local b="$1"
  case "$b" in
    .git|.venv|.tox|.cache|.pytest_cache|.mypy_cache|.ruff_cache|.next|.skill-build|.backups|.close-state|.loop-state|.session-archive|.recall-state|__pycache__|node_modules|vendor|dist|build|Koš|Kos|_*) return 0 ;;
  esac
  return 1
}

gen_table() {
  printf '| File | What it is |\n|---|---|\n'
  if [ -z "$FOLDERS_ONLY" ]; then for f in "$DIR"/* "$DIR"/.[!.]* "$DIR"/..?*; do
    [ -f "$f" ] || continue
    [ -L "$f" ] && continue
    # A manifest never lists itself — INDEX.md IS this table's output file (merge mode),
    # so a self-row is noise (and a whole-repo root INDEX would list "INDEX.md" about itself).
    b="$(basename "$f")"
    skip_file "$b" && continue
    [ -n "$INCLUDE_HIDDEN" ] || case "$b" in .*) continue ;; esac
    if [ -z "$ALL_FILES" ]; then
      case "$b" in *.md) ;; *) continue ;; esac
    fi
    if [ "${b##*.}" = "md" ]; then
      d="$(desc_line "$f" | redact_secrets | esc_cell)"
    else
      # Never inspect non-Markdown content. Configs and binaries may contain secrets;
      # the tree needs their path and type, not their values.
      d="$(file_kind "$b" | esc_cell)"
    fi
    printf '| `%s` | %s |\n' "$b" "$d"
  done; fi
  if [ -z "$FILES_ONLY" ]; then for sub in "$DIR"/*/ "$DIR"/.[!.]*/ "$DIR"/..??*/; do
    [ -d "$sub" ] || continue
    b="$(basename "$sub")"
    # Trash, dot/underscore, and build/vendor dirs are noise in any manifest (root rollup incl.).
    skip_dir "$b" && continue
    [ -n "$INCLUDE_HIDDEN" ] || case "$b" in .*) continue ;; esac
    # Never read/describe a symlinked folder — its target may live outside the repo (trust
    # boundary; the injected map goes into the session context). audit 2026-07-12.
    [ -L "${sub%/}" ] && continue
    lead=""
    for cand in SKILL.md INDEX.md README.md KNIHOVNA.md; do
      [ -f "$sub$cand" ] && { lead="$sub$cand"; break; }
    done
    # First *.md (glob, sorted) — glob loop is space/newline-safe, unlike `ls | head`.
    if [ -z "$lead" ]; then for cand in "$sub"*.md; do [ -f "$cand" ] && { lead="$cand"; break; }; done; fi
    if [ -n "$lead" ] && [ -f "$lead" ]; then
      printf '| `%s/` | %s |\n' "$b" "$(desc_line "$lead" | redact_secrets | esc_cell)"
    else
      # Count .md recursively — a folder of sub-folders (e.g. domeny/<d>/*.md) has 0 top-level files
      # but is NOT empty; maxdepth-1 made the map lie "(folder, 0 files)" about rich content.
      if [ -n "$ALL_FILES" ]; then
        n="$(find "$sub" -type f 2>/dev/null | wc -l | tr -d ' ')"
        printf '| `%s/` | (folder, %s files) |\n' "$b" "$n"
      else
        n="$(find "$sub" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
        printf '| `%s/` | (folder, %s .md files) |\n' "$b" "$n"
      fi
    fi
  done; fi
}

gen_compact() {
  # SessionStart needs the complete path inventory, not every derived description. A large
  # plain-text hook output can be dropped by the host as one unit; names-only keeps the boot
  # context bounded while physical INDEX.md files retain their detailed tables.
  local wrote="" f sub b
  if [ -z "$FOLDERS_ONLY" ]; then for f in "$DIR"/* "$DIR"/.[!.]* "$DIR"/..?*; do
    [ -f "$f" ] || continue
    [ -L "$f" ] && continue
    b="$(basename "$f")"
    skip_file "$b" && continue
    [ -n "$INCLUDE_HIDDEN" ] || case "$b" in .*) continue ;; esac
    if [ -z "$ALL_FILES" ]; then case "$b" in *.md) ;; *) continue ;; esac; fi
    printf '%s\t' "$b"
    wrote=1
  done; fi
  if [ -z "$FILES_ONLY" ]; then for sub in "$DIR"/*/ "$DIR"/.[!.]*/ "$DIR"/..??*/; do
    [ -d "$sub" ] || continue
    [ -L "${sub%/}" ] && continue
    b="$(basename "$sub")"
    skip_dir "$b" && continue
    [ -n "$INCLUDE_HIDDEN" ] || case "$b" in .*) continue ;; esac
    printf '%s/\t' "$b"
    wrote=1
  done; fi
  [ -n "$wrote" ] || printf '(empty)'
  printf '\n'
}

default_header() {
  printf '# INDEX — %s\n\n' "$TITLE"
  printf '> Folder manifest: what it contains + one-line context.\n'
}

if [ -n "$COMPACT" ]; then
  gen_compact
elif [ -n "$TABLE_ONLY" ]; then
  # Injection view: only the manifest table (what lives where), no header/kernel fluff.
  # The curated header stays in the INDEX.md file on disk for when it's opened directly.
  # NB: --table-only WINS over --merge-into (callers pass them separately — index_inject.sh
  # calls --merge-into to refresh the file, then --table-only to print; never both at once).
  gen_table
elif [ -n "$MERGE" ]; then
  if [ -f "$MERGE" ] && grep -qF "gen_index:auto" "$MERGE"; then
    hdr="$(sed '/gen_index:auto/,$d' "$MERGE")"   # everything above the marker = curated header
  elif [ -f "$MERGE" ]; then
    # File exists but carries NO gen_index:auto marker — it is hand-written or from another tool.
    # Overwriting would SILENTLY DESTROY its content (no marker = no way to know where a curated
    # header ends). Conservative default: refuse and tell the caller. Add the marker line once to
    # opt the folder into managed regeneration. (BLOCKER, audit 2026-07-12: --whole-repo would
    # otherwise wipe a freshly hand-written INDEX.md on the next boot.)
    echo "gen_index: $MERGE has no gen_index:auto marker — refusing to overwrite (would lose hand-written content). Add the marker line to opt in." >&2
    exit 3
  else
    hdr="$(default_header)"
  fi
  # Atomic write via mktemp (a fixed "$MERGE.tmp" lets two concurrent merges clobber
  # the same temp; mktemp gives each its own) + rename. dirname, NOT ${MERGE%/*}:
  # on a bare filename ("INDEX.md") the %/* expansion is a no-op and mktemp would
  # target a path INSIDE a nonexistent dir named INDEX.md (0.1.33 audit fix).
  merge_dir="$(dirname "$MERGE")"
  tmp="$(mktemp "$merge_dir/.gen_index.XXXXXX" 2>/dev/null)" || { echo "gen_index: mktemp failed" >&2; exit 1; }
  { printf '%s\n' "$hdr"; printf '%s\n\n' "$MARKER"; gen_table; } > "$tmp" 2>/dev/null \
    && mv "$tmp" "$MERGE" 2>/dev/null || { rm -f "$tmp" 2>/dev/null; exit 1; }
else
  default_header; echo; gen_table
fi
exit 0
